### ISSUE TITLE
Update API Reference Documentation

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub.github.io#17]
The [API Reference Documentation](https://github.com/openintegrationhub/openintegrationhub.github.io/blob/master/docs/6%20-%20ReferenceDocumentation/APIReferenceOverview.md) needs to be updated. Some newer services are missing and the older ones should be checked to make sure the docs are up to date.

**Comment by IoannisLafiotis** [comment]
Due to insufficient resources some of the services are not always deployed on the cluster, therefore their respective swagger files cannot be rendered and return a 404 error.

**Comment by RobinBrinkmann** [comment]
https://github.com/openintegrationhub/openintegrationhub/issues/1194
