### ISSUE TITLE
Improve Example Flows in Deployment Guidelines

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub.github.io#19]
The deployment guides are meant to help with an initial test setup of the Open Integration Hub currently do not provide ideal test flow scenarios. We already made some changes to the [local guide ](https://github.com/openintegrationhub/openintegrationhub.github.io/blob/master/docs/3%20-%20Deployment/GCPInstallationGuide.md) to have an example with two code components. The [GCP guide ](https://github.com/openintegrationhub/openintegrationhub.github.io/blob/master/docs/3%20-%20Deployment/GCPInstallationGuide.md) still provides an older example. The flow example should be the same and but also generally updated. 

We need to provide more documentation and explanation, as well as check and change what images we use for the installation setups. Components have to be compatible with recent changes and should be provided under openintegrationhub github org / dockerhub and not other partners.

**Comment by weberjm** [comment]
For this task, the Flow creation steps in each Deployment are part of a "User Tutorial" which is separate from the rest of the installation/deployment steps. This Tutorial should be broken out either as a separate page, or as a page snippet which can be included in both pages to display the same content, without risk of future out-of-sync problems.

**Comment by RobinBrinkmann** [comment]
With #35 we will break out the Tutorial to a separate page.
